[discrete]
== PartiQL Specification License

Copyright (C) 2019 Amazon.com Inc. or Affiliates ("`Amazon`").

This Agreement sets forth the terms under which Amazon is making the PartiQL Specification available to you.

[discrete]
=== Copyrights

Permission is hereby granted, free of charge, to you to use, copy, publish, and/or distribute, the Specification subject to the following conditions:

* The above copyright notice and this permission notice shall be included in all copies of the Specification.
* You may not modify, merge, sublicense, and/or sell copies of the Specification.

[discrete]
=== Patents

Subject to the terms and conditions of this Agreement, Amazon hereby grants to you a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable (except as stated in this section) patent license to make, have made, use, offer to sell, sell, import, and otherwise transfer implementations of the Specification that implement and are compliant with all relevant portions of the Specification ("`Compliant Implementations`").
Notwithstanding the foregoing, no patent license is granted to any technologies that may be necessary to make or use any product or portion thereof that complies with the Specification but are not themselves expressly set forth in the Specification.

If you institute patent litigation against any entity (including a
cross-claim or counterclaim in a lawsuit) alleging that Compliant
Implementations of the Specification constitute direct or contributory
patent infringement, then any patent licenses granted to You under this
Agreement shall terminate as of the date such litigation is filed.

THE SPECIFICATION IS PROVIDED "`AS IS`", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL AMAZON BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SPECIFICATION, IMPLEMENTATIONS OF
THE SPECIFICATION, OR THE USE OR OTHER DEALINGS IN THE SPECIFICATION.

Any sample code included in the Specification, unless otherwise
specified, is licensed under the MIT No Attribution License.
